/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    return true;
  },
  createHandlerBoundToURL('/index.html')
);

// ---------------------------------------------------------------------------
// 1. API & Content Caching
// ---------------------------------------------------------------------------

// Content Cache (Lessons/Quizzes pages - Fallback)
registerRoute(
  ({ request, url }) => {
    if (request.method !== 'GET') return false;
    return (
      url.origin === self.location.origin &&
      (url.pathname.includes('/lessons/') || url.pathname.includes('/quizzes/'))
    );
  },
  new StaleWhileRevalidate({
    cacheName: 'content-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// ---------------------------------------------------------------------------
// 2. Asset Caching (Images, Fonts, Styles)
// ---------------------------------------------------------------------------

// Local Images
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(?:png|gif|jpg|jpeg|svg|webp)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: 'local-images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// Firebase Storage Images (User uploads/Diagrams)
registerRoute(
  ({ url }) => url.origin.includes('firebasestorage.googleapis.com'),
  new StaleWhileRevalidate({
    cacheName: 'firebase-storage-images',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 300, maxAgeSeconds: 60 * 24 * 60 * 60 }),
    ],
  })
);

// Google Drive Images (converted links in ContentRenderer)
registerRoute(
  ({ url }) => url.origin.includes('drive.google.com') || url.origin.includes('googleusercontent.com'),
  new StaleWhileRevalidate({
    cacheName: 'google-drive-images',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }), // 0 is critical for opaque responses
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// ---------------------------------------------------------------------------
// 3. External Resources (CDNs, Fonts) - FIX FOR CRASHES
// ---------------------------------------------------------------------------

// Google Fonts Stylesheets
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Google Fonts Webfont Files (CacheFirst for performance)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxAgeSeconds: 365 * 24 * 60 * 60, maxEntries: 30 }),
    ],
  })
);

// External CDNs (KaTeX, etc. from index.html)
registerRoute(
  ({ url }) => url.origin === 'https://cdn.jsdelivr.net' || url.origin === 'https://unpkg.com',
  new StaleWhileRevalidate({
    cacheName: 'static-libs-cdn',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// ---------------------------------------------------------------------------
// 4. Lifecycle & Cleanup
// ---------------------------------------------------------------------------

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('activate', (event) => {
  const currentCaches = [
    'precache-v2', 'runtime', 'content-cache', 
    'local-images', 'firebase-storage-images', 'google-drive-images',
    'google-fonts-stylesheets', 'google-fonts-webfonts', 'static-libs-cdn'
  ]; 
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (!currentCaches.includes(cacheName)) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});