/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') {
      return false;
    }
    if (url.pathname.startsWith('/_')) {
      return false;
    }
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }
    return true;
  },
  createHandlerBoundToURL('/index.html')
);

// Content Cache (Lessons/Quizzes pages - Fallback)
registerRoute(
  ({ request, url }) => {
    // 1. Ignore non-GET requests (POST, PUT, DELETE, etc.) to prevent Cache API errors
    if (request.method !== 'GET') {
      return false;
    }
    
    // 2. Check if the origin matches and path contains lessons/quizzes
    return (
      url.origin === self.location.origin &&
      (url.pathname.includes('/lessons/') || url.pathname.includes('/quizzes/'))
    );
  },
  new StaleWhileRevalidate({
    cacheName: 'content-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100, // Increased max entries
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// 1. Caching for Local Images (Your assets folder)
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(?:png|gif|jpg|jpeg|svg|webp)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: 'local-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// 2. Caching for Firebase Storage Images (User uploads/Diagrams)
// CRITICAL: This enables images hosted on Firebase to be visible offline
registerRoute(
  ({ url }) => url.origin.includes('firebasestorage.googleapis.com'),
  new StaleWhileRevalidate({
    cacheName: 'firebase-storage-images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200], // 0 is important for CORS/Opaque responses
      }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 Days
      }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Clean up old caches
self.addEventListener('activate', (event) => {
  // Added 'local-images' and 'firebase-storage-images' to the allowlist
  const currentCaches = ['precache-v2', 'runtime', 'content-cache', 'local-images', 'firebase-storage-images']; 
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (!currentCaches.includes(cacheName)) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});